# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVShows' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVShows

  pod 'Alamofire', '~> 4.7'
  pod 'CodableAlamofire', '~> 1.1'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'PromiseKit/CorePromise', '~> 6.0'
  pod 'PromiseKit/Alamofire'


  target 'TVShowsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TVShowsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
